### ISSUE TITLE
Errors loading data, and creating new model in tutorial

### ISSUE THREAD

**Issue by robot-love** [PerceptiLabs/PerceptiLabs#155]
Following the tutorials, I attempt to load the covid-19 tutorial dataset `data.csv` file, I get the following error message:

> Error: Couldn't infer data types

I'm allowed to proceed. In the `Training Settings` I click `Customize`, and after some attempt to load, encounter the following error message:

> Couldn't get model recommendation due to: Error: Network Error

and I can't continue from there.

**Comment by mastro-hub** [comment]
Hello.

I have the same issue. 

(base) PS C:\---\---> C:\---\---\Miniconda3\Scripts\perceptilabs                                            2021-08-01 14:15:22.112629: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-08-01 14:15:22.119284: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-08-01 14:15:28.040570: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-08-01 14:15:28.048804: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-01 14:15:28.068198: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: RO-00004119
2021-08-01 14:15:28.077860: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: RO-00004119
INFO: Could not find files for the given pattern(s).
PerceptiLabs: Your environment does not have git installed, so interactions with GitHub will not be available
PerceptiLabs: Starting
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs:    rendering-kernel on port 5001
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    rendering-kernel on port 5001
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    rendering-kernel on port 5001
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    rendering-kernel on port 5001
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    rendering-kernel on port 5001
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    rendering-kernel on port 5001
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    rendering-kernel on port 5001
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    rendering-kernel on port 5001
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    rendering-kernel on port 5001

**Comment by med100s** [comment]
same

**Comment by robot-love** [comment]
Solved it. The `blinker` dependency wasn't installing correctly and had to be added separately from the `perceptilabs` package. Installing it fixed the problem.
