### ISSUE TITLE
skip run the the previous components

### ISSUE THREAD

**Issue by yuanjiexiong** [PerceptiLabs/PerceptiLabs#45]
Support lazy run mode, skip running the the previous components if the previous components's options and inputs not change.

**Comment by Rolun** [comment]
Hi,
It should only run the changed component and anything dependent on it. Did you encounter a situation where it did not behave like this?

Best regards,
Robert

**Comment by yuanjiexiong** [comment]
Sorry it's my fault.

How can i rerun all node, some time i  need rerun the components, like the random data or custom component  web crawler.

**Comment by Rolun** [comment]
In the workspace while previewing the components you can re-run them by doing any change. This can be as easy as changing a parameter or just updating the custom code with an extra space somewhere. We will look into a "Force Update" feature for the components though :) 

In the workspace it is just the preview though, as soon as you Run the model it will re-run everything from scratch and take the latest.
